In [1]:
import pandas as pd
import numpy as np
import sqlite3
from useful_functions import *

In [2]:
tables_to_join = ["tSoilNutrients", "tSample", 'tPlantDNA']
common_column = "sample_id"
full_df = import_all_data(tables_to_join, common_column)
full_df.head()

,sample_id,OM,ENR,CEC,pH,BpH,Phosphorus,Potassium,Calcium,Magnesium,...,collect_date,sample_id,V1,V2,species,PC1,PC2,PC3,PC4,PC5
0,RRL1,19.4,150.0,9.5,5.9,6.77,10.0,180.0,1200.0,153.0,...,6/25/2021,RRL1,0.753244,0.246756,exaltata,0.194769,0.048276,-0.023880,-0.017138,-0.039842
1,RRL2,21.3,150.0,8.4,6.0,6.80,9.0,170.0,1069.0,148.0,...,6/25/2021,RRL2,0.708412,0.291588,exaltata,0.154924,0.071277,0.000923,-0.025830,0.005592
2,RRL3,22.5,150.0,7.1,5.9,6.81,16.0,119.0,853.0,153.0,...,6/25/2021,RRL3,0.778046,0.221954,exaltata,0.187750,0.035009,-0.016006,-0.012529,-0.011169
3,RRL4,28.9,150.0,8.1,5.5,6.72,17.0,114.0,878.0,148.0,...,6/25/2021,RRL4,0.720367,0.279633,exaltata,0.167167,0.046053,-0.032754,-0.016192,-0.028988
4,RRL5,25.6,150.0,8.4,6.0,6.80,17.0,139.0,1059.0,162.0,...,6/25/2021,RRL5,0.572487,0.427513,exaltata,0.099801,0.089800,0.000613,-0.004979,0.017524

In [4]:
full_df = full_df.T.drop_duplicates().T

In [5]:
full_df.head()

,sample_id,OM,ENR,CEC,pH,BpH,Phosphorus,Potassium,Calcium,Magnesium,...,site_id,collect_date,V1,V2,species,PC1,PC2,PC3,PC4,PC5
0,RRL1,19.4,150.0,9.5,5.9,6.77,10.0,180.0,1200.0,153.0,...,RRL,6/25/2021,0.753244,0.246756,exaltata,0.194769,0.048276,-0.02388,-0.017138,-0.039842
1,RRL2,21.3,150.0,8.4,6.0,6.8,9.0,170.0,1069.0,148.0,...,RRL,6/25/2021,0.708412,0.291588,exaltata,0.154924,0.071277,0.000923,-0.02583,0.005592
2,RRL3,22.5,150.0,7.1,5.9,6.81,16.0,119.0,853.0,153.0,...,RRL,6/25/2021,0.778046,0.221954,exaltata,0.18775,0.035009,-0.016006,-0.012529,-0.011169
3,RRL4,28.9,150.0,8.1,5.5,6.72,17.0,114.0,878.0,148.0,...,RRL,6/25/2021,0.720367,0.279633,exaltata,0.167167,0.046053,-0.032754,-0.016192,-0.028988
4,RRL5,25.6,150.0,8.4,6.0,6.8,17.0,139.0,1059.0,162.0,...,RRL,6/25/2021,0.572487,0.427513,exaltata,0.099801,0.0898,0.000613,-0.004979,0.017524

In [7]:
full_df.columns

Index(['sample_id', 'OM', 'ENR', 'CEC', 'pH', 'BpH', 'Phosphorus', 'Potassium',
       'Calcium', 'Magnesium', 'Sulfur', 'Sodium', 'Zinc', 'Manganese', 'Iron',
       'Copper', 'Boron', 'site_id', 'collect_date', 'V1', 'V2', 'species',
       'PC1', 'PC2', 'PC3', 'PC4', 'PC5'],
      dtype='object')

In [10]:
full_df = full_df.drop(['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'V1'], axis = 1)

In [11]:
full_df.head()

,sample_id,OM,ENR,CEC,pH,BpH,Phosphorus,Potassium,Calcium,Magnesium,...,Sodium,Zinc,Manganese,Iron,Copper,Boron,site_id,collect_date,V2,species
0,RRL1,19.4,150.0,9.5,5.9,6.77,10.0,180.0,1200.0,153.0,...,38.0,2.2,68.0,82.0,4.1,0.3,RRL,6/25/2021,0.246756,exaltata
1,RRL2,21.3,150.0,8.4,6.0,6.8,9.0,170.0,1069.0,148.0,...,19.0,3.0,93.0,75.0,4.5,0.4,RRL,6/25/2021,0.291588,exaltata
2,RRL3,22.5,150.0,7.1,5.9,6.81,16.0,119.0,853.0,153.0,...,18.0,3.8,97.0,100.0,2.9,0.2,RRL,6/25/2021,0.221954,exaltata
3,RRL4,28.9,150.0,8.1,5.5,6.72,17.0,114.0,878.0,148.0,...,17.0,3.1,79.0,131.0,2.6,0.2,RRL,6/25/2021,0.279633,exaltata
4,RRL5,25.6,150.0,8.4,6.0,6.8,17.0,139.0,1059.0,162.0,...,18.0,4.7,130.0,103.0,1.9,0.3,RRL,6/25/2021,0.427513,exaltata

In [12]:
full_df.to_csv('namit_data.csv')

In [3]:
import pandas as pd
import numpy as np
import sqlite3
import plotly.express as px
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.manifold import TSNE
import statsmodels
import statsmodels.api as sm
from statsmodels.multivariate.manova import MANOVA
from scipy import stats

from useful_functions import *

In [4]:
tables_to_join = ["tSoilMicrobeGenera", "tSample"]
common_column = "sample_id"
full_df = import_all_data(tables_to_join, common_column)
full_df.shape

full_df = full_df.T.drop_duplicates().T

df = full_df.copy()

subdf = df.copy()

origin_pivoted_df = subdf.pivot(index=['sample_id', 'site_id'], columns='genera', values='relative_abundance')
origin_pivoted_df.shape

row_sum = origin_pivoted_df.sum(axis=1)

origin_pivoted_df = origin_pivoted_df.reset_index()

genera_col = origin_pivoted_df.columns
genera_col = genera_col.drop(['sample_id','site_id'])

sub_pivot = origin_pivoted_df[genera_col].astype(float)

for row in range(sub_pivot.shape[0]):
    sub_pivot.loc[row] = sub_pivot.loc[row]/row_sum[row]

new_sum = sub_pivot.sum(axis=1)
new_sum

origin_pivoted_df[genera_col] = sub_pivot

origin_pivoted_df.head()

row_sum = origin_pivoted_df[genera_col].sum(axis=1)
print(row_sum)

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
303    1.0
304    1.0
305    1.0
306    1.0
307    1.0
Length: 308, dtype: float64

In [5]:
sum_row = origin_pivoted_df[genera_col].sum()

abundant_genera = sum_row.nlargest(100)

select_columns = (abundant_genera.index).tolist()
select_columns.insert(0, 'sample_id')
select_columns.insert(0, 'site_id')

origin_pivoted_df = origin_pivoted_df[select_columns]

origin_pivoted_df.head()

genera,site_id,sample_id,Bacteria|Proteobacteria|Alphaproteobacteria|Rhizobiales|Bradyrhizobiaceae|Bradyrhizobium,Bacteria|Proteobacteria|Gammaproteobacteria|Pseudomonadales|Pseudomonadaceae|Pseudomonas,Bacteria|Actinobacteria|Actinobacteria|Streptomycetales|Streptomycetaceae|Streptomyces,Bacteria|Cyanobacteria||Synechococcales|Synechococcaceae|Synechococcus,Bacteria|Cyanobacteria||Synechococcales|Synechococcaceae|Thermosynechococcus,Bacteria|Proteobacteria|Alphaproteobacteria|Sphingomonadales|Sphingomonadaceae|Sphingomonas,Bacteria|Proteobacteria|Gammaproteobacteria|Xanthomonadales|Xanthomonadaceae|Stenotrophomonas,Bacteria|Actinobacteria|Actinobacteria|Corynebacteriales|Mycobacteriaceae|Mycobacterium,...,Bacteria|Actinobacteria|Actinobacteria|Micrococcales|Microbacteriaceae|Agromyces,Bacteria|Proteobacteria|Betaproteobacteria|Burkholderiales|Oxalobacteraceae|Herbaspirillum,Bacteria|Proteobacteria|Betaproteobacteria|Burkholderiales|Oxalobacteraceae|Janthinobacterium,Bacteria|Cyanobacteria||Nostocales|Nostocaceae|Nostoc,Bacteria|Proteobacteria|Betaproteobacteria|Neisseriales|Chromobacteriaceae|Chromobacterium,Bacteria|Proteobacteria|Betaproteobacteria|Neisseriales|Chromobacteriaceae|Pseudogulbenkiania,Bacteria|Proteobacteria|Betaproteobacteria|Burkholderiales|Burkholderiaceae|Ralstonia,Bacteria|Proteobacteria|Gammaproteobacteria|Xanthomonadales|Rhodanobacteraceae|Dokdonella,Bacteria|Proteobacteria|Betaproteobacteria|Burkholderiales|Oxalobacteraceae|Collimonas,Bacteria|Proteobacteria|Gammaproteobacteria|Enterobacterales|Enterobacteriaceae|Enterobacter
0,BLD,BLDTT49,0.075678,0.022733,0.067763,0.000000,0.0,0.030082,0.017133,0.025928,...,0.002042,0.002457,0.000973,0.000000,0.004199,0.002321,0.004382,0.003419,0.001433,0.000566
1,BLD,BLDTT50,0.111201,0.026321,0.074591,0.000000,0.0,0.018377,0.009608,0.034008,...,0.002910,0.005508,0.003183,0.000000,0.001909,0.001401,0.003139,0.002476,0.009142,0.001433
2,BLD,BLDTT51,0.105425,0.036915,0.039351,0.000420,0.0,0.020228,0.013341,0.013334,...,0.002185,0.002796,0.001313,0.000013,0.005122,0.004098,0.002546,0.004251,0.002167,0.000377
3,BLD,BLDTT52,0.104595,0.038922,0.030471,0.000286,0.0,0.031615,0.016605,0.007149,...,0.002013,0.003993,0.002332,0.000000,0.005346,0.005107,0.004944,0.004777,0.002847,0.000293
4,BTU,BTU12,0.093086,0.135410,0.050359,0.000000,0.0,0.026569,0.017308,0.031169,...,0.003735,0.003941,0.003109,0.000000,0.001364,0.002248,0.002776,0.002091,0.002415,0.000822

In [6]:
origin_pivoted_df.to_csv('soil_microbe_scale_to_one.csv')

In [7]:
opdf = origin_pivoted_df.copy()
microbe_cols = abundant_genera.index

In [8]:
opdf[microbe_cols] = StandardScaler().fit_transform(opdf[microbe_cols])

In [9]:
opdf.head()

genera,site_id,sample_id,Bacteria|Proteobacteria|Alphaproteobacteria|Rhizobiales|Bradyrhizobiaceae|Bradyrhizobium,Bacteria|Proteobacteria|Gammaproteobacteria|Pseudomonadales|Pseudomonadaceae|Pseudomonas,Bacteria|Actinobacteria|Actinobacteria|Streptomycetales|Streptomycetaceae|Streptomyces,Bacteria|Cyanobacteria||Synechococcales|Synechococcaceae|Synechococcus,Bacteria|Cyanobacteria||Synechococcales|Synechococcaceae|Thermosynechococcus,Bacteria|Proteobacteria|Alphaproteobacteria|Sphingomonadales|Sphingomonadaceae|Sphingomonas,Bacteria|Proteobacteria|Gammaproteobacteria|Xanthomonadales|Xanthomonadaceae|Stenotrophomonas,Bacteria|Actinobacteria|Actinobacteria|Corynebacteriales|Mycobacteriaceae|Mycobacterium,...,Bacteria|Actinobacteria|Actinobacteria|Micrococcales|Microbacteriaceae|Agromyces,Bacteria|Proteobacteria|Betaproteobacteria|Burkholderiales|Oxalobacteraceae|Herbaspirillum,Bacteria|Proteobacteria|Betaproteobacteria|Burkholderiales|Oxalobacteraceae|Janthinobacterium,Bacteria|Cyanobacteria||Nostocales|Nostocaceae|Nostoc,Bacteria|Proteobacteria|Betaproteobacteria|Neisseriales|Chromobacteriaceae|Chromobacterium,Bacteria|Proteobacteria|Betaproteobacteria|Neisseriales|Chromobacteriaceae|Pseudogulbenkiania,Bacteria|Proteobacteria|Betaproteobacteria|Burkholderiales|Burkholderiaceae|Ralstonia,Bacteria|Proteobacteria|Gammaproteobacteria|Xanthomonadales|Rhodanobacteraceae|Dokdonella,Bacteria|Proteobacteria|Betaproteobacteria|Burkholderiales|Oxalobacteraceae|Collimonas,Bacteria|Proteobacteria|Gammaproteobacteria|Enterobacterales|Enterobacteriaceae|Enterobacter
0,BLD,BLDTT49,0.454615,-0.534682,0.516568,-0.527530,-0.526522,0.450981,-0.055760,0.243119,...,-0.057351,0.166343,-0.443427,-0.381089,1.083657,0.085697,1.290700,0.680734,-0.144403,-0.192949
1,BLD,BLDTT50,1.225566,-0.461380,0.671539,-0.527530,-0.526522,-0.235709,-0.294753,0.456557,...,0.350598,1.835742,0.404173,-0.381089,-0.102973,-0.281551,0.588649,0.197712,1.552851,-0.081637
2,BLD,BLDTT51,1.100202,-0.244894,-0.128307,-0.521421,-0.526522,-0.127155,-0.176177,-0.089549,...,0.009934,0.351747,-0.312963,-0.378676,1.562038,0.794950,0.253502,1.107175,0.017054,-0.217253
3,BLD,BLDTT52,1.082191,-0.203894,-0.329874,-0.523376,-0.526522,0.540923,-0.072504,-0.252935,...,-0.070904,1.006470,0.078035,-0.381089,1.677994,1.197763,1.607664,1.376569,0.166813,-0.227976
4,BTU,BTU12,0.832403,1.767664,0.121541,-0.527530,-0.526522,0.244857,-0.050180,0.381578,...,0.738936,0.978318,0.375987,-0.381089,-0.385510,0.056696,0.383090,0.000428,0.071645,-0.160021

In [10]:
opdf.to_csv('soil_microbe_with_standard_scaler.csv')